export default [
  {
    id: 0,
    title: "Men's Shoes",
    items: [
      "Skate Shoes",
      "Boat Shoes",
      "Fashion Sneakers",
      "Formal \u0026 Tuxedo",
      "Loafers \u0026 Slip-ons",
      "Outdoor",
      "Sandals",
      "Slippers",
      "Work \u0026 Safety",
      "More...",
    ],
  },
  {
    id: 1,
    title: "Women's Shoes",
    items: [
      "Skate Shoes",
      "Boat Shoes",
      "Fashion Sneakers",
      "Formal \u0026 Tuxedo",
      "Loafers \u0026 Slip-ons",
      "Outdoor",
      "Sandals",
      "Slippers",
      "Work \u0026 Safety",
      "More...",
    ],
  },
  {
    id: 2,
    title: "Kids's Shoes",
    items: [
      "Skate Shoes",
      "Boat Shoes",
      "Fashion Sneakers",
      "Formal \u0026 Tuxedo",
      "Loafers \u0026 Slip-ons",
      "Outdoor",
      "Sandals",
      "Slippers",
      "Work \u0026 Safety",
      "More...",
    ],
  },
  {
    id: 3,
    title: "Acessories",
    items: ["Bags", "Scarfs", "Belts", "Hats", "More..."],
  },
];
