export default [
  {
    prodId: 1,
    name: "trainers",
    style: "trainers",
    color: "white",
    size: "four",
    gender: "boy",
    imgUrl: "/images/kids-trainer.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 2,
    name: "hiking-boots",
    style: "hiking-boots",
    color: "brown",
    size: "nine",
    gender: "women",
    imgUrl: "/images/fur-lined-hiking-boot.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 3,
    name: "skate-shoes",
    style: "skate-shoes",
    color: "beige",
    size: "seven",
    gender: "men",
    imgUrl: "/images/basket-ball-shoe.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 4,
    name: "ladies-boots",
    style: "ladies-boots",
    color: "black",
    size: "nine",
    gender: "women",
    imgUrl: "/images/fur-lined-ladies-boot.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 5,
    name: "hiking-boots",
    style: "hiking-boots",
    color: "brown",
    size: "seven",
    gender: "women",
    imgUrl: "/images/fur-lined-hiking-boot.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 6,
    name: "trainers",
    style: "trainers",
    color: "white",
    size: "four",
    gender: "girl",
    imgUrl: "/images/kids-trainer.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 7,
    name: "ladies-boots",
    style: "ladies-boots",
    color: "black",
    size: "six",
    gender: "women",
    imgUrl: "/images/fur-lined-ladies-boot.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 8,
    name: "hiking-boots",
    style: "hiking-boots",
    color: "brown",
    size: "five",
    gender: "women",
    imgUrl: "/images/fur-lined-hiking-boot.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 9,
    name: "trainers",
    style: "trainers",
    color: "white",
    size: "six",
    gender: "boy",
    imgUrl: "/images/kids-trainer.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 10,
    name: "skate-shoes",
    style: "skate-shoes",
    color: "beige",
    size: "six",
    gender: "men",
    imgUrl: "/images/basket-ball-shoe.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 11,
    name: "skate-shoes",
    style: "skate-shoes",
    color: "beige",
    size: "eight",
    gender: "men",
    imgUrl: "/images/basket-ball-shoe.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 12,
    name: "ladies-boots",
    style: "ladies-boots",
    color: "black",
    size: "seven",
    gender: "women",
    imgUrl: "/images/fur-lined-ladies-boot.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 13,
    name: "skate-shoes",
    style: "skate-shoes",
    color: "beige",
    size: "nine",
    gender: "men",
    imgUrl: "/images/basket-ball-shoe.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 14,
    name: "trainers",
    style: "trainers",
    color: "white",
    size: "five",
    gender: "girl",
    imgUrl: "/images/kids-trainer.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 15,
    name: "ladies-boots",
    style: "ladies-boots",
    color: "black",
    size: "eight",
    gender: "women",
    imgUrl: "/images/fur-lined-ladies-boot.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 16,
    name: "hiking-boots",
    style: "hiking-boots",
    color: "brown",
    size: "six",
    gender: "women",
    imgUrl: "/images/fur-lined-hiking-boot.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
];
