export default [
  {
    prodId: 1,
    name: "trainers",
    style: "trainers",
    color: "white",
    size: "five",
    gender: "boy",
    imgUrl: "/images/sized-png/trainers-white-blk-175.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 2,
    name: "fur-lined boots",
    style: "boots",
    color: "brown",
    size: "eight",
    gender: "women",
    imgUrl: "/images/sized-png/ladies-fur-lined-boots-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 3,
    name: "skate-shoe",
    style: "skate-shoe",
    color: "beige",
    size: "seven",
    gender: "men",
    imgUrl: "/images/sized-png/skate-shoes-beige-175.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 4,
    name: "high-heels",
    style: "high-heels",
    color: "beige",
    size: "seven",
    gender: "women",
    imgUrl: "/images/sized-png/ladies-high-heels-175.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 5,
    name: "ladies-laced-shoe",
    style: "laced-shoe",
    color: "brown",
    size: "five",
    gender: "women",
    imgUrl: "/images/sized-png/ladies-laced-shoes-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 6,
    name: "stilletos",
    style: "stilletos",
    color: "red",
    size: "six",
    gender: "women",
    imgUrl: "/images/sized-png/ladies-shoes-red-stilleto-175.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 7,
    name: "ladies-ballet-shoe",
    style: "ballet-shoes",
    color: "red",
    size: "six",
    gender: "women",
    imgUrl: "/images/sized-png/red-slipper-shoes-175.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 8,
    name: "ladies-hiking-boots",
    style: "hiking-boots",
    color: "brown",
    size: "seven",
    gender: "women",
    imgUrl: "/images/sized-png/ladies-hiking-boots-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 9,
    name: "mens-boots",
    style: "boots",
    color: "brown",
    size: "six",
    gender: "men",
    imgUrl: "/images/sized-png/men-boots-175.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 10,
    name: "mens-dress-shoe",
    style: "dress-shoes",
    color: "brown",
    size: "six",
    gender: "men",
    imgUrl: "/images/sized-png/mens-dress-shoes-175.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 11,
    name: "mens-laced-shoe",
    style: "laced-shoes",
    color: "beige",
    size: "eight",
    gender: "men",
    imgUrl: "/images/sized-png/mens-laced-shoes-175.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 12,
    name: "skate-shoe",
    style: "skate-shoes",
    color: "blue",
    size: "seven",
    gender: "women",
    imgUrl: "/images/sized-png/skate-shoes-blue-175.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 13,
    name: "basketball shoe",
    style: "trainers",
    color: "white",
    size: "nine",
    gender: "men",
    imgUrl: "/images/sized-png/mens-trainers-black-175.png",
    price: "90.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 14,
    name: "basketball shoe",
    style: "trainers",
    color: "grey",
    size: "eight",
    gender: "men",
    imgUrl: "/images/sized-png/trainers-grey-175.png",
    price: "40.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 15,
    name: "trainers",
    style: "trainers",
    color: "red",
    size: "seven",
    gender: "women",
    imgUrl: "/images/sized-png/trainers-red-175.png",
    price: "70.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 16,
    name: "running shoe",
    style: "trainers",
    color: "pink",
    size: "six",
    gender: "women",
    imgUrl: "/images/sized-png/trainers-pink-blue-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 17,
    name: "running shoe",
    style: "trainers",
    color: "blue",
    size: "six",
    gender: "men",
    imgUrl: "/images/sized-png/trainers-light-blue-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 18,
    name: "running shoe",
    style: "trainers",
    color: "black",
    size: "seven",
    gender: "men",
    imgUrl: "/images/sized-png/trainers-running-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 19,
    name: "mens-loafers",
    style: "loafers",
    color: "blue",
    size: "seven",
    gender: "men",
    imgUrl: "/images/sized-png/mens-loafers-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 20,
    name: "running shoe",
    style: "trainers",
    color: "white",
    size: "seven",
    gender: "women",
    imgUrl: "/images/sized-png/trainers-white-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
  {
    prodId: 21,
    name: "running shoe",
    style: "trainers",
    color: "grey",
    size: "seven",
    gender: "women",
    imgUrl: "/images/sized-png/trainers-grey-white-175.png",
    price: "80.00",
    cartImg: "/images/shoppingcart.png",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elitReiciendis nobis eius error, animi iusto est voluptates,ipsa autem asperiores culpa.",
    all: "all",
  },
];
