export default [
  {
    id: 1,
    name: "all",
    value: "all",
    options: [{ id: 1, value: "all", displayValue: "All shoes" }],
  },
  {
    id: 2,
    name: "gender",
    value: "gender",
    options: [
      { id: 1, value: "men", displayValue: "Men" },
      { id: 2, value: "women", displayValue: "Women" },
      { id: 3, value: "boy", displayValue: "Boy" },
      { id: 4, value: "girl", displayValue: "Girl" },
    ],
  },
  {
    id: 3,
    name: "style",
    value: "style",
    options: [
      { id: 1, value: "trainers", displayValue: "Trainers" },
      { id: 2, value: "high-heels", displayValue: "High Heels" },
      { id: 3, value: "skate-shoe", displayValue: "Skate Shoes" },
      { id: 4, value: "boots", displayValue: "Boots" },
      { id: 5, value: "laced-shoe", displayValue: "Laced Shoe" },
      { id: 6, value: "stilletos", displayValue: "Stillettos" },
      { id: 7, value: "ballet-shoe", displayValue: "Ballet Shoe" },
      { id: 8, value: "dress-shoe", displayValue: "Dress Shoe" },
      { id: 9, value: "loafers", displayValue: "Loafers" },
    ],
  },
  {
    id: 4,
    name: "size",
    value: "size",
    options: [
      { id: 1, value: "four", displayValue: "Four" },
      { id: 2, value: "five", displayValue: "Five" },
      { id: 3, value: "six", displayValue: "Six" },
      { id: 4, value: "seven", displayValue: "Seven" },
      { id: 5, value: "eight", displayValue: "Eight" },
      { id: 6, value: "nine", displayValue: "Nine" },
      { id: 7, value: "ten", displayValue: "Ten" },
    ],
  },
  {
    id: 5,
    name: "color",
    value: "color",
    options: [
      { id: 1, value: "white", displayValue: "White" },
      { id: 2, value: "black", displayValue: "Black" },
      { id: 3, value: "brown", displayValue: "Brown" },
      { id: 4, value: "beige", displayValue: "Beige" },
      { id: 5, value: "blue", displayValue: "Blue" },
      { id: 6, value: "grey", displayValue: "Grey" },
      { id: 7, value: "pink", displayValue: "Pink" },
      { id: 8, value: "red", displayValue: "Red" },
    ],
  },
];
