import Head from "next/head";
import Layout from "../components/Layout";
import BannerImg from "../components/homepage/bannerImg";
import HomePageBoxes from "../components/homepage/homepageBoxes";
import AccordianMenu from "../components/accordianMenu";
import FindShoes from "../components/homepage/FindShoes";
import productData from "./api/json-data/Productdata-copy";
import accordian from "./api/json-data/Accordiondata.js";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  const visibility = false;

  const sidebarVisibility = (e) => {
    e.preventDefault();
    console.log(e);
  };

  return (
    <Layout>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main id="main-content" className="clearfix">
          <button
            id="sidebar-toggle-btn"
            type="button"
            onClick={sidebarVisibility}
            aria-label="secondary menu toggle button"
          >
            SIDE
          </button>

          <aside
            className={`left-side-content ${visibility ? "is-expanded" : " "}`}
          >
            <FindShoes />
            <AccordianMenu accordian={accordian} />
          </aside>

          <section id="right-content-section" className="group">
            {/* <BannerImg banner={banner} /> */}
            <BannerImg />

            <h1 id="right-content-section-header">Featured</h1>
            <HomePageBoxes productData={productData} />
          </section>
        </main>
      </>
    </Layout>
  );
}
