import Head from "next/head";
import Layout from "../components/Layout";
import BannerImg from "../components/HomePage/BannerImg";
import FrontPageBoxes from "../components/HomePage/FrontpageBoxes";
import FindShoes from "../components/HomePage/FindShoes";
//import Image from "next/image";
//import Link from "next/link";
import productData from "../pages/api/Productdata";

export default function Home() {
  const visibility = false;

  const sidebarVisibility = (e) => {
    e.preventDefault();
    console.log(e);
  };

  return (
    <Layout>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main id="main-content" className="clearfix">
          <button
            id="sidebar-toggle-btn"
            type="button"
            onClick={sidebarVisibility}
            aria-label="secondary menu toggle button"
          >
            SIDE
          </button>

          <aside
            className={`left-side-content ${visibility ? "is-expanded" : " "}`}
          >
            <FindShoes />
            {/* <FindShoesAccord /> */}
          </aside>

          <section id="right-content-section" className="group">
            {/* <BannerImg banner={banner} /> */}
            <BannerImg />

            <h1 id="right-content-section-header">Featured</h1>
            <FrontPageBoxes productData={productData} />
          </section>
        </main>
      </>
    </Layout>
  );
}
