import React, { useState } from 'react'
import Head from 'next/head'
//import {Product , Accordian} from '../types/index'
import 'bootstrap/dist/css/bootstrap.min.css'
import Layout from '../components/Layout'
import BannerImg from '../components/homepage/bannerImg'
import HomePageBoxes from '../components/homepage/homepageBoxes'
import AccordianMenu from '../components/accordianMenu'
import FindShoes from '../components/homepage/FindShoes'
import { selectAllAccordian, fetchAccordian, getAccordianStatus } from '../features/accordian/accordianSlice'
import { selectAllProducts, fetchProducts, getProductsStatus} from "../features/products/productSlice";
import { useAppSelector, useAppDispatch } from '../app/store';
import { useEffect } from "react";

const Home = () => {

  const dispatch  = useAppDispatch();
  // get Products
  const productItems = useAppSelector(selectAllProducts);
  const productItemsStatus = useAppSelector(getProductsStatus);
  //const productItemsError = useAppSelector(getProductsError);

  // acoordian data
  const accordianItems = useAppSelector(selectAllAccordian);
  const accordianDataStatus = useAppSelector(getAccordianStatus);
  //const accordianDataError = useAppSelector(getAccordianError);

  useEffect(() => {
    if (productItemsStatus === 'idle') {
        dispatch(fetchProducts())
    }
  }, [productItemsStatus,dispatch])

  useEffect(() => {
    if(accordianDataStatus === 'idle'){
      dispatch(fetchAccordian())
    }
  }, [accordianDataStatus,dispatch])


  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const {products} = productItems as any

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const {accordian} = accordianItems as any

  //const {product, accordian} = props.products as HomePageProds;

  const [visibility, setVisibility] = useState<boolean>(false)

  //console.log(products, accordian)

  /** API slice */
  // const {
  //   data
  // } = useGetProductsQuery()

  // const otherproducts = data?.product as Product[]
  // const otheraccordian = data?.accordian as AccordianProp[]

  //const {product, accordian} = data as HomePageProds;


  const sidebarVisibility = (e: { preventDefault: () => void }) => {
    e.preventDefault()
    setVisibility(!visibility)
  }

  return (
    <Layout>
      <>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main id="main-content" className="clearfix">
          <button
            id="sidebar-toggle-btn"
            type="button"
            onClick={sidebarVisibility}
            aria-label="secondary menu toggle button"
          >
            SIDE
          </button>

          <aside
            className={`left-side-content ${visibility ? 'is-expanded' : ' '}`}
          >
            <FindShoes />
            <AccordianMenu accordianData={accordian} />
          </aside>

          <section id="right-content-section" className="group">
            <BannerImg />

            <h1 id="right-content-section-header">Featured</h1>
            <HomePageBoxes productData={products} />
          </section>
        </main>
      </>
    </Layout>
  )
}

export default Home

