import React, { useState } from "react";
import Head from "next/head";
import Layout from "../components/Layout";
import BannerImg from "../components/homepage/bannerImg";
import HomePageBoxes from "../components/homepage/homepageBoxes";
import AccordianMenu from "../components/accordianMenu";
import FindShoes from "../components/homepage/FindShoes";
import { handler } from "./api";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home(props) {
  const [accordianData] = useState(props.accordian);
  const [productData] = useState(props.productData);
  const [visibility, setVisibility] = useState(false);

  const sidebarVisibility = (e) => {
    e.preventDefault();
    setVisibility(!visibility);
  };

  return (
    <Layout>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main id="main-content" className="clearfix">
          <button
            id="sidebar-toggle-btn"
            type="button"
            onClick={sidebarVisibility}
            aria-label="secondary menu toggle button"
          >
            SIDE
          </button>

          <aside
            className={`left-side-content ${visibility ? "is-expanded" : " "}`}
          >
            <FindShoes />
            <AccordianMenu accordianData={accordianData} />
          </aside>

          <section id="right-content-section" className="group">
            <BannerImg />

            <h1 id="right-content-section-header">Featured</h1>
            <HomePageBoxes productData={productData} />
          </section>
        </main>
      </>
    </Layout>
  );
}

export async function getServerSideProps() {
  const productData = await handler("http://localhost:8000/api/products");
  const accordian = await handler("http://localhost:8000/api/accordiondata");

  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: {
      productData,
      accordian,
    },
  };
}
